apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{DEPLOYMENT_NAME}}
  labels:
    app: staticsite
    environment: {{ENVIRONMENT}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staticsite
      environment: {{ENVIRONMENT}}
  template:
    metadata:
      labels:
        app: staticsite
        environment: {{ENVIRONMENT}}
    spec:
      containers:
      - name: staticsite
        image: {{IMAGE_NAME}}:{{IMAGE_TAG}}
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: ENVIRONMENT
          value: "{{ENVIRONMENT}}"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: staticsite-service-{{ENVIRONMENT}}
  labels:
    app: staticsite
    environment: {{ENVIRONMENT}}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: staticsite
    environment: {{ENVIRONMENT}}
  sessionAffinity: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: staticsite-config-{{ENVIRONMENT}}
  labels:
    app: staticsite
    environment: {{ENVIRONMENT}}
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        
        server {
            listen       80;
            server_name  localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
                try_files $uri $uri/ /index.html;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
    }