apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-site-ingress-{{ENVIRONMENT}}
  labels:
    app: static-site
    environment: {{ENVIRONMENT}}
  annotations:
    # AWS Load Balancer Controller annotations
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: '200'
    # SSL and security
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # Optional: Add your domain certificate ARN
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:region:account:certificate/certificate-id
spec:
  rules:
  - host: static-site-{{ENVIRONMENT}}.yourdomain.com  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-site-service-{{ENVIRONMENT}}
            port:
              number: 80
  # Default rule (if no host specified)
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-site-service-{{ENVIRONMENT}}
            port:
              number: 80